# Generates disks for various thingamabobs.
def generateDisks(body, diskRadius, targetPath):
    diskObj = open(targetPath + "/Configs/" + body + "_JETS" + ".cfg","x")
    diskObj.write(
        "@Kopernicus\n"
        "{\n"
        "    Body\n"
        "    {\n"
        "        name = " + str(body) + "_JET1" + "\n"
        "        Tag = InfD_NeutronJets\n"
        "        Template\n"
        "        {\n"
        "            name = Jool\n"
        "        }\n"
        "        Properties\n"
        "        {\n"
        "            description = \n"
        "            radius = 1000\n"
        "            mass = 420\n"
        "            rotationPeriod = 420\n"
        "            initialRotation = 0\n"
        "            sphereOfInfluence = 1\n"
        "            selectable = False\n"
        "        }\n"
        "        Orbit\n"
        "        {\n"
        "            referenceBody = " + str(body) + "\n"
        "            semiMajorAxis = 1\n"
        "            period = 100000000000000000000000\n"
        "            argumentOfPeriapsis = 90\n"
        "            mode = 0\n"
        "            icon = NONE\n"
        "        }\n"
        "        Rings\n"
        "        {\n"
        "        \n"
        "            Ring\n"
        "            {\n"
        "                innerRadius = 301\n"
        "                outerRadius = 2E+11\n"
        "                steps = 10000\n"
        "                texture = InfiniteDiscoveries/Textures/Misc/neutronJet.dds\n"
        "                tiles = 2\n"
        "                color = 1,1,1,1\n"
        "                unlit = True\n"
        "                useNewShader = False\n"
        "                penumbraMultiplier = 10\n"
        "                angle = 90\n"
        "                longitudeOfAscendingNode = 0\n"
        "                lockRotation = False\n"
        "                rotationPeriod = 1260\n"
        "            }\n"
        "            // Disks\n"
        "            Ring\n"
        "            {\n"
        "                innerRadius = 301\n"
        "                outerRadius = " + str(diskRadius) + "\n"
        "                steps = 10000\n"
        "                texture = InfiniteDiscoveries/Textures/Misc/neutronDisk.dds\n"
        "                tiles = 2\n"
        "                color = 1,1,1,1\n"
        "                unlit = True\n"
        "                useNewShader = False\n"
        "                penumbraMultiplier = 10\n"
        "                angle = -4\n"
        "                longitudeOfAscendingNode = 0\n"
        "                lockRotation = False\n"
        "                rotationPeriod = 1450\n"
        "            }\n"
        "            Ring\n"
        "            {\n"
        "                innerRadius = 301\n"
        "                outerRadius = " + str(diskRadius) + "\n"
        "                steps = 10000\n"
        "                texture = InfiniteDiscoveries/Textures/Misc/neutronDisk.dds\n"
        "                tiles = 2\n"
        "                color = 1,1,1,1\n"
        "                unlit = True\n"
        "                useNewShader = False\n"
        "                penumbraMultiplier = 10\n"
        "                angle = -2\n"
        "                longitudeOfAscendingNode = 0\n"
        "                lockRotation = False\n"
        "                rotationPeriod = 1350\n"
        "            }\n"
        "            Ring\n"
        "            {\n"
        "                innerRadius = 301\n"
        "                outerRadius = " + str(diskRadius) + "\n"
        "                steps = 10000\n"
        "                texture = InfiniteDiscoveries/Textures/Misc/neutronDisk.dds\n"
        "                tiles = 2\n"
        "                color = 1,1,1,1\n"
        "                unlit = True\n"
        "                useNewShader = False\n"
        "                penumbraMultiplier = 10\n"
        "                angle = 0\n"
        "                longitudeOfAscendingNode = 0\n"
        "                lockRotation = False\n"
        "                rotationPeriod = 1250\n"
        "            }\n"
        "            Ring\n"
        "            {\n"
        "                innerRadius = 301\n"
        "                outerRadius = " + str(diskRadius) + "\n"
        "                steps = 10000\n"
        "                texture = InfiniteDiscoveries/Textures/Misc/neutronDisk.dds\n"
        "                tiles = 2\n"
        "                color = 1,1,1,1\n"
        "                unlit = True\n"
        "                useNewShader = False\n"
        "                penumbraMultiplier = 10\n"
        "                angle = 2\n"
        "                longitudeOfAscendingNode = 0\n"
        "                lockRotation = False\n"
        "                rotationPeriod = 1150\n"
        "            }\n"
        "            Ring\n"
        "            {\n"
        "                innerRadius = 301\n"
        "                outerRadius = " + str(diskRadius) + "\n"
        "                steps = 10000\n"
        "                texture = InfiniteDiscoveries/Textures/Misc/neutronDisk.dds\n"
        "                tiles = 2\n"
        "                color = 1,1,1,1\n"
        "                unlit = True\n"
        "                useNewShader = False\n"
        "                penumbraMultiplier = 10\n"
        "                angle = 4\n"
        "                longitudeOfAscendingNode = 0\n"
        "                lockRotation = False\n"
        "                rotationPeriod = 1050\n"
        "            }\n"
        "        }\n"
        "    }\n"
        "    Body\n"
        "    {\n"
        "        name = " + str(body) + "_JET2" + "\n"
        "        Tag = InfD_NeutronJets\n"
        "        Template\n"
        "        {\n"
        "            name = Jool\n"
        "        }\n"
        "        Properties\n"
        "        {\n"
        "            description = \n"
        "            radius = 1000\n"
        "            mass = 420\n"
        "            rotationPeriod = 420\n"
        "            initialRotation = 90\n"
        "            sphereOfInfluence = 1\n"
        "            selectable = False\n"
        "        }\n"
        "        Orbit\n"
        "        {\n"
        "            referenceBody = " + str(body) + "\n"
        "            semiMajorAxis = 1\n"
        "            period = 100000000000000000000000\n"
        "            argumentOfPeriapsis = 90\n"
        "            mode = 0\n"
        "            icon = NONE\n"
        "        }\n"
        "        Rings\n"
        "        {\n"
        "            Ring\n"
        "            {\n"
        "                innerRadius = 301\n"
        "                outerRadius = 2E+11\n"
        "                steps = 10000\n"
        "                texture = InfiniteDiscoveries/Textures/Misc/neutronJet.dds\n"
        "                tiles = 2\n"
        "                color = 1,1,1,1\n"
        "                unlit = True\n"
        "                useNewShader = False\n"
        "                penumbraMultiplier = 10\n"
        "                angle = 90\n"
        "                longitudeOfAscendingNode = 0\n"
        "                lockRotation = False\n"
        "                rotationPeriod = 1260\n"
        "            }\n"
        "            // Disks\n"
        "            Ring\n"
        "            {\n"
        "                innerRadius = 301\n"
        "                outerRadius = " + str(diskRadius) + "\n"
        "                steps = 10000\n"
        "                texture = InfiniteDiscoveries/Textures/Misc/neutronDisk.dds\n"
        "                tiles = 2\n"
        "                color = 1,1,1,1\n"
        "                unlit = True\n"
        "                useNewShader = False\n"
        "                penumbraMultiplier = 10\n"
        "                angle = -4\n"
        "                longitudeOfAscendingNode = 0\n"
        "                lockRotation = False\n"
        "                rotationPeriod = 1450\n"
        "            }\n"
        "            Ring\n"
        "            {\n"
        "                innerRadius = 301\n"
        "                outerRadius = " + str(diskRadius) + "\n"
        "                steps = 10000\n"
        "                texture = InfiniteDiscoveries/Textures/Misc/neutronDisk.dds\n"
        "                tiles = 2\n"
        "                color = 1,1,1,1\n"
        "                unlit = True\n"
        "                useNewShader = False\n"
        "                penumbraMultiplier = 10\n"
        "                angle = -2\n"
        "                longitudeOfAscendingNode = 0\n"
        "                lockRotation = False\n"
        "                rotationPeriod = 1350\n"
        "            }\n"
        "            Ring\n"
        "            {\n"
        "                innerRadius = 301\n"
        "                outerRadius = " + str(diskRadius) + "\n"
        "                steps = 10000\n"
        "                texture = InfiniteDiscoveries/Textures/Misc/neutronDisk.dds\n"
        "                tiles = 2\n"
        "                color = 1,1,1,1\n"
        "                unlit = True\n"
        "                useNewShader = False\n"
        "                penumbraMultiplier = 10\n"
        "                angle = 0\n"
        "                longitudeOfAscendingNode = 0\n"
        "                lockRotation = False\n"
        "                rotationPeriod = 1250\n"
        "            }\n"
        "            Ring\n"
        "            {\n"
        "                innerRadius = 301\n"
        "                outerRadius = " + str(diskRadius) + "\n"
        "                steps = 10000\n"
        "                texture = InfiniteDiscoveries/Textures/Misc/neutronDisk.dds\n"
        "                tiles = 2\n"
        "                color = 1,1,1,1\n"
        "                unlit = True\n"
        "                useNewShader = False\n"
        "                penumbraMultiplier = 10\n"
        "                angle = 2\n"
        "                longitudeOfAscendingNode = 0\n"
        "                lockRotation = False\n"
        "                rotationPeriod = 1150\n"
        "            }\n"
        "            Ring\n"
        "            {\n"
        "                innerRadius = 301\n"
        "                outerRadius = " + str(diskRadius) + "\n"
        "                steps = 10000\n"
        "                texture = InfiniteDiscoveries/Textures/Misc/neutronDisk.dds\n"
        "                tiles = 2\n"
        "                color = 1,1,1,1\n"
        "                unlit = True\n"
        "                useNewShader = False\n"
        "                penumbraMultiplier = 10\n"
        "                angle = 4\n"
        "                longitudeOfAscendingNode = 0\n"
        "                lockRotation = False\n"
        "                rotationPeriod = 1050\n"
        "            }\n"
        "        }\n"
        "    }\n"
        "}\n"
    )