import random

# Generate a bunch of wormholes for some reason
def generateWormholes(seed, alphabet, base_dir, allPlanets, StarAmount):
    WormholeRNG = random.Random()
    WormholeRNG.seed(seed)
    #print(str(len(allPlanets)) + "<------------------------------------------------------------------------ all planata legth")
    if len(allPlanets) > 0:
        wormholesConfig = open(base_dir / "Configs" / f"wormholes{WormholeRNG.randint(0,100000)}.cfg", "x") # random number to avoid existing file errors.
        wormholesConfig.write(
            "@Kopernicus:LAST[InfiniteDiscoveries]:HAS[@InfiniteDiscoveriesSettings:HAS[#Wormholes[?rue]]]:NEEDS[KopernicusExpansion]\n"
            "{\n"
        )
        for i in range(0,StarAmount + 1):
            target1 = allPlanets[WormholeRNG.randint(0,len(allPlanets)-1)]
            while True:
                target2 = allPlanets[WormholeRNG.randint(0,len(allPlanets)-1)]
                if not target2 == target1:
                    break
            wormholeName1 = alphabet[WormholeRNG.randint(0,len(alphabet)-1)] + alphabet[WormholeRNG.randint(0,len(alphabet)-1)] + alphabet[WormholeRNG.randint(0,len(alphabet)-1)] + "-" + str(WormholeRNG.randint(0,100000))
            wormholeName2 = alphabet[WormholeRNG.randint(0,len(alphabet)-1)] + alphabet[WormholeRNG.randint(0,len(alphabet)-1)] + alphabet[WormholeRNG.randint(0,len(alphabet)-1)] + "-" + str(WormholeRNG.randint(0,100000))
            singularCfg = open(base_dir / "Visuals" / "Singularity" / f"{wormholeName1}-{wormholeName2}_SNG.cfg", "x")
            singularCfg.write(
                "Singularity\n"
                "{\n"
                "    Singularity_object\n"
                "    {\n"
                "        name = " + wormholeName1 + "\n"
                "        gravity = 5\n"
                "        hideCelestialBody = true\n"
                "        useAccretionDisk = false\n"
                "        wormholeTarget = " + wormholeName2 + "\n"
                "    }\n"
                "    Singularity_object\n"
                "    {\n"
                "        name = " + wormholeName2 + "\n"
                "        gravity = 5\n"
                "        hideCelestialBody = true\n"
                "        useAccretionDisk = false\n"
                "        wormholeTarget = " + wormholeName1 + "\n"
                "    }\n"
                "}\n"
            )
            wormholesConfig.write(
                "    Body\n"
                "    {\n"
                "        name = " + wormholeName1 + "\n"
                "        cacheFile = InfiniteDiscoveries/Cache/" + wormholeName1 + ".bin\n"
                "        Template\n"
                "        {\n"
                "            name = Dres\n"
                "            removeAllPQSMods = True\n"
                "        }\n"
                "        Properties\n"
                "        {\n"
                "            displayName = " + wormholeName1 + "\n"
                "            description = A mysterious object, supposedly going under 5 kilometers on here will send you to another star system...\n"
                "            radius = 100000\n"
                "            geeASL = 10\n"
                "            tidallyLocked = false\n"
                "            rotationPeriod = 10000\n"
                "        }\n"
                "        Wormhole\n"
                "        {\n"
                "            partner = " + wormholeName2 + "\n"
                "            influenceAltitude = 8000\n"
                "            jumpMaxAltitude = 5000\n"
                "            jumpMinAltitude = 10\n"
                "            entryMessage = Entering a wormhole... We are not responsible for any casualties within, before, or after entering the wormhole. We also do not know where you may end up, good luck!\n"
                "            exitMessage = Succesfully survived spacetime bending. Welcome to " + target1 + "!\n"
                "            heatRate = 0.1\n"
                "            entryMsgDuration = 7\n"
                "            exitMsgDuration = 7\n"
                "        }\n"
                "        ScaledVersion\n"
                "        {\n"
                "            type = Vacuum\n"
                "            fadeStart = 7000\n"
                "            fadeEnd = 10000\n"
                "            Material\n"
                "            {\n"
                "                texture = InfiniteDiscoveries/Textures/Misc/literallynothing.png\n"
                "                normals = InfiniteDiscoveries/Textures/Misc/literallyjustablanknormalmap.dds\n"
                "                color = 1,1,1,1\n"
                "                specColor = 0.05,0.05,0.05,1\n"
                "                shininess = 1\n"
                "            }\n"
                "        }\n"
                "        Orbit\n"
                "        {\n"
                "            referenceBody = " + target1 + "\n"
                "            inclination = " + str(WormholeRNG.randint(-15,15)) + "\n"
                "            eccentricity = 0\n"
                "            semiMajorAxis = " + str(WormholeRNG.randint(5000000,50000000)) + "\n"
                "            longitudeOfAscendingNode = " + str(WormholeRNG.randint(0,360)) + "\n"
                "            argumentOfPeriapsis = " + str(WormholeRNG.randint(0,360)) + "\n"
                "            epoch = 0\n"
                "            color = 0.2,0.2,0.2,0.2\n"
                "            iconTexture = InfiniteDiscoveries/Textures/Misc/wormholeIco.png\n"
                "        }\n"
                "        PQS\n"
                "        {\n"
                "            Mods\n"
                "            {			\n"
                "                VertexHeightMap\n"
                "                {\n"
                "                    map = InfiniteDiscoveries/Textures/Misc/literallynothing.png\n"
                "                    offset = -99999\n"
                "                    deformity = 0\n"
                "                    scaleDeformityByRadius = False\n"
                "                    order = 10\n"
                "                    enabled = True\n"
                "                }\n"
                "                VertexColorMap\n"
                "                {\n"
                "                    map = InfiniteDiscoveries/Textures/Misc/literallynothing.png\n"
                "                    order = 90\n"
                "                    enabled = True\n"
                "                    name = VertexColorMap\n"
                "                    index = 0\n"
                "                } \n"
                "            }\n"
                "        }\n"
                "    }\n"
                "    Body\n"
                "    {\n"
                "        name = " + wormholeName2 + "\n"
                "        cacheFile = InfiniteDiscoveries/Cache/" + wormholeName2 + ".bin\n"
                "        Template\n"
                "        {\n"
                "            name = Dres\n"
                "            removeAllPQSMods = True\n"
                "        }\n"
                "        Properties\n"
                "        {\n"
                "            displayName = " + wormholeName2 + "\n"
                "            description = A mysterious object, supposedly going under 5 kilometers on here will send you to another star system...\n"
                "            radius = 100000\n"
                "            geeASL = 10\n"
                "            tidallyLocked = false\n"
                "            rotationPeriod = 10000\n"
                "        }\n"
                "        Wormhole\n"
                "        {\n"
                "            partner = " + wormholeName1 + "\n"
                "            influenceAltitude = 8000\n"
                "            jumpMaxAltitude = 5000\n"
                "            jumpMinAltitude = 10\n"
                "            entryMessage = Entering a wormhole... We are not responsible for any casualties within, before, or after entering the wormhole. We also do not know where you may end up, good luck!\n"
                "            exitMessage = Succesfully survived spacetime bending. Welcome to " + target2 + "!\n"
                "            heatRate = 0.1\n"
                "            entryMsgDuration = 7\n"
                "            exitMsgDuration = 7\n"
                "        }\n"
                "        ScaledVersion\n"
                "        {\n"
                "            type = Vacuum\n"
                "            fadeStart = 7000\n"
                "            fadeEnd = 10000\n"
                "            Material\n"
                "            {\n"
                "                texture = InfiniteDiscoveries/Textures/Misc/literallynothing.png\n"
                "                normals = InfiniteDiscoveries/Textures/Misc/literallyjustablanknormalmap.dds\n"
                "                color = 1,1,1,1\n"
                "                specColor = 0.05,0.05,0.05,1\n"
                "                shininess = 1\n"
                "            }\n"
                "        }\n"
                "        Orbit\n"
                "        {\n"
                "            referenceBody = " + target2 + "\n"
                "            inclination = " + str(WormholeRNG.randint(-15,15)) + "\n"
                "            eccentricity = 0\n"
                "            semiMajorAxis = " + str(WormholeRNG.randint(5000000,50000000)) + "\n"
                "            longitudeOfAscendingNode = " + str(WormholeRNG.randint(0,360)) + "\n"
                "            argumentOfPeriapsis = " + str(WormholeRNG.randint(0,360)) + "\n"
                "            epoch = 0\n"
                "            color = 0.2,0.2,0.2,0.2\n"
                "            iconTexture = InfiniteDiscoveries/Textures/Misc/wormholeIco.png\n"
                "        }\n"
                "        PQS\n"
                "        {\n"
                "            Mods\n"
                "            {			\n"
                "                VertexHeightMap\n"
                "                {\n"
                "                    map = InfiniteDiscoveries/Textures/Misc/literallynothing.png\n"
                "                    offset = -99999\n"
                "                    deformity = 0\n"
                "                    scaleDeformityByRadius = False\n"
                "                    order = 10\n"
                "                    enabled = True\n"
                "                }\n"
                "                VertexColorMap\n"
                "                {\n"
                "                    map = InfiniteDiscoveries/Textures/Misc/literallynothing.png\n"
                "                    order = 90\n"
                "                    enabled = True\n"
                "                    name = VertexColorMap\n"
                "                    index = 0\n"
                "                } \n"
                "            }\n"
                "        }\n"
                "    }\n"
            )
        wormholesConfig.write(
            "}\n"
        )