import random

# Adds parallax scatters.
def addParallaxScatter(seed, cfg, planetName, haslife, lifeclr, radius):
    pSctrRNG = random.Random()
    pSctrRNG.seed(seed)
    radiusDiv = 600 / (radius/1000)

    cfg.write(
        "ParallaxScatters\n"
        "{\n"
        "   body = " + planetName + "\n"
        "   minimumSubdivision = 2\n"
    )
    cfg.write(
        "   Scatter\n"
        "   {\n"
        "       name = SmallRocks\n"
        "       model = InfiniteDiscoveries/Visuals/Parallax/Models/Rocks/RockSmall/rock\n"
        "       updateFPS = 1\n"
        "       cullingRange = 20\n"
        "       cullingLimit = -30\n"
        "       alignToTerrainNormal = True\n"
        "       SubdivisionSettings\n"
        "       {\n"
        "           subdivisionLevel = 1\n"
        "           subdivisionRangeMode = FixedRange\n"
        "           subdivisionRange = 900\n"
        "       }\n"
        "       DistributionNoise\n"
        "       {\n"
        "           mode = Persistent\n"
        "           _Frequency = 180000\n"
        "           _Persistence = 0.300000012\n"
        "           _Lacunarity = 2\n"
        "           _Octaves = 6\n"
        "           _Seed = " + str(pSctrRNG.randint(0,10000)) + "\n"
        "           _NoiseType = 1\n"
        "           _NoiseQuality = Standard\n"
        "       }\n"
        "       Distribution\n"
        "       {\n"
        "           _Seed = 1\n"
        "           _SpawnChance = 1\n"
        "           _Range = 160\n"
        "           _PopulationMultiplier = "+ str((40/radiusDiv)/radiusDiv) + "\n"
    )
    cfg.write(
        "           _SizeNoiseStrength = 1\n"
        "           _MinScale = 0.02,0.02,0.02\n"
        "           _MaxScale = 1,1,1\n"
        "           _CutoffScale = 0.150000006\n"
        "           _SteepPower = 8\n"
        "           _SteepContrast = 4.5\n"
        "           _SteepMidpoint = 0.731000006\n"
        "           _NormalDeviance = 0.12\n"
        "           _MinAltitude = -1000\n"
        "           _MaxAltitude = 20000\n"
        "           _RangePow = 3\n"
        "           LODs\n"
        "           {\n"
        "               LOD\n"
        "               {\n"
        "                   model = InfiniteDiscoveries/Visuals/Parallax/Models/Rocks/RockSmall/rock1\n"
        "                   _MainTex = parent\n"
        "                   range = 80\n"
        "                   billboard = False\n"
        "               }\n"
        "               LOD\n"
        "               {\n"
        "                   model = InfiniteDiscoveries/Visuals/Parallax/Models/Rocks/RockSmall/rock1\n"
        "                   _MainTex = parent\n"
        "                   range = 200\n"
        "                   billboard = False\n"
        "               }\n"
        "           }\n"
        "       }\n"
        "       Material\n"
        "       {\n"
        "           shader = Custom/ParallaxInstancedUV\n"
        "           _MainColor = 1,1,1,1\n"
        "           _SubColor = 1,1,1,1\n"
        "           _ColorNoiseStrength = 1\n"
        "           _MainTex = InfiniteDiscoveries/Visuals/Parallax/Models/Rocks/RockSmall/textureclr.dds\n"
        "           _EdgeBumpMap = InfiniteDiscoveries/Visuals/Parallax/Models/Rocks/RockSmall/texturenrm.dds\n"
        "           _Metallic = 0.25\n"
        "           _Gloss = 5\n"
        "           _NormalSpecularInfluence = 1\n"
        "           _Hapke = 0.300000012\n"
        "           _BumpScale = 1\n"
        "           _FresnelPower = 4\n"
        "           _MainTexScale = 1,1\n"
        "           _EdgeBumpMapScale = 1,1\n"
        "           _EmissionColor = 0,0,0,1\n"
        "           _MetallicTint = 0.5,0.5,0.5,1\n"
        "           _Color = 0.5,0.5,0.5,1\n"
        "           _FresnelColor = 0.0799999982,0.0799999982,0.0799999982,1\n"
        "       }\n"
        "       SubObjects\n"
        "       {\n"
        "       }\n"
        "   }\n"
    )
    cfg.write(
        "   Scatter\n"
        "   {\n"
        "       name = MedRocks\n"
        "       model = InfiniteDiscoveries/Visuals/Parallax/Models/Rocks/RockMedium/rock\n"
        "       updateFPS = 1\n"
        "       cullingRange = 20\n"
        "       cullingLimit = -30\n"
        "       alignToTerrainNormal = True\n"
        "       collideable = True\n"
        "       maxObjects = 20000\n"
        "       //collisionMesh = InfiniteDiscoveries/Visuals/Parallax/Models/Rocks/RockMedium/rock1\n"
        "       SubdivisionSettings\n"
        "       {\n"
        "           subdivisionLevel = 1\n"
        "           subdivisionRangeMode = FixedRange\n"
        "           subdivisionRange = 1400\n"
        "       }\n"
        "       DistributionNoise\n"
        "       {\n"
        "           mode = Persistent\n"
        "           _Frequency = 18000\n"
        "           _Persistence = 0.300000012\n"
        "           _Lacunarity = 2\n"
        "           _Octaves = 6\n"
        "           _Seed = " + str(pSctrRNG.randint(0,10000)) + "\n"
        "           _NoiseType = 1\n"
        "           _NoiseQuality = Standard\n"
        "       }\n"
        "       Distribution\n"
        "       {\n"
        "           _Seed = 0\n"
        "           _SpawnChance = 1\n"
        "           _Range = 1200\n"
        "           _PopulationMultiplier = "+ str((5/radiusDiv)/radiusDiv) + "\n"
    )
    cfg.write(
        "           _SizeNoiseStrength = 1\n"
        "           _MinScale = 0.2,0.2,0.2\n"
        "           _MaxScale = 5,5,5\n"
        "           _CutoffScale = 0.5\n"
        "           _SteepPower = 8\n"
        "           _SteepContrast = 4.5\n"
        "           _SteepMidpoint = 0.731000006\n"
        "           _NormalDeviance = 0.2\n"
        "           _MinAltitude = -1000\n"
        "           _MaxAltitude = 20000\n"
        "           _RangePow = 4\n"
        "           LODs\n"
        "           {\n"
        "               LOD\n"
        "               {\n"
        "                   model = InfiniteDiscoveries/Visuals/Parallax/Models/Rocks/RockMedium/rock1\n"
        "                   _MainTex = parent\n"
        "                   range = 200\n"
        "                   billboard = False\n"
        "               }\n"
        "               LOD\n"
        "               {\n"
        "                   model = InfiniteDiscoveries/Visuals/Parallax/Models/Rocks/RockMedium/rock1\n"
        "                   _MainTex = parent\n"
        "                   range = 500\n"
        "                   billboard = False\n"
        "               }\n"
        "           }\n"
        "       }\n"
        "       Material\n"
        "       {\n"
        "           shader = Custom/ParallaxInstancedUV\n"
        "           _MainColor = 1,1,1,1\n"
        "           _SubColor = 1,1,1,1\n"
        "           _ColorNoiseStrength = 1\n"
        "           _MainTex = InfiniteDiscoveries/Visuals/Parallax/Models/Rocks/RockMedium/textureclr.dds\n"
        "           _EdgeBumpMap = InfiniteDiscoveries/Visuals/Parallax/Models/Rocks/RockMedium/texturenrm.dds\n"
        "           _Metallic = 0.25\n"
        "           _Gloss = 2\n"
        "           _NormalSpecularInfluence = 1\n"
        "           _Hapke = 1\n"
        "           _BumpScale = 1\n"
        "           _FresnelPower = 4\n"
        "           _MainTexScale = 1,1\n"
        "           _EdgeBumpMapScale = 1,1\n"
        "           _EmissionColor = 0,0,0,1\n"
        "           _MetallicTint = 0.5,0.5,0.5,1\n"
        "           _Color = 0.5,0.5,0.5,1\n"
        "           _FresnelColor = 0.2,0.2,0.2,1\n"
        "       }\n"
        "       SubObjects\n"
        "       {\n"
        "       }\n"
        "   }\n"
    )   
    # NEW JAGGED ROCKERS
    cfg.write(
        "   Scatter\n"
        "   {\n"
        "       name = JaggedRocks\n"
        "       model = InfiniteDiscoveries/Visuals/Parallax/Models/Rocks/RockJagged/rock\n"
        "       updateFPS = 1\n"
        "       cullingRange = 20\n"
        "       cullingLimit = -30\n"
        "       alignToTerrainNormal = True\n"
        "       collideable = True\n"
        "       maxObjects = 20000\n"
        "       //collisionMesh = InfiniteDiscoveries/Visuals/Parallax/Models/Rocks/RockJagged/rock1\n"
        "       SubdivisionSettings\n"
        "       {\n"
        "           subdivisionLevel = 1\n"
        "           subdivisionRangeMode = FixedRange\n"
        "           subdivisionRange = 1400\n"
        "       }\n"
        "       DistributionNoise\n"
        "       {\n"
        "           mode = Persistent\n"
        "           _Frequency = 1800\n"
        "           _Persistence = 0.300000012\n"
        "           _Lacunarity = 2\n"
        "           _Octaves = 6\n"
        "           _Seed = " + str(pSctrRNG.randint(0,10000)) + "\n"
        "           _NoiseType = 1\n"
        "           _NoiseQuality = Standard\n"
        "       }\n"
        "       Distribution\n"
        "       {\n"
        "           _Seed = 0\n"
        "           _SpawnChance = 1\n"
        "           _Range = 1200\n"
        "           _PopulationMultiplier = "+ str((15/radiusDiv)/radiusDiv) + "\n"
    )
    cfg.write(
        "           _SizeNoiseStrength = 1\n"
        "           _MinScale = 1,1,1\n"
        "           _MaxScale = 3,3,3\n"
        "           _CutoffScale = 0.5\n"
        "           _SteepPower = 8\n"
        "           _SteepContrast = 4.5\n"
        "           _SteepMidpoint = 0.731000006\n"
        "           _NormalDeviance = 0.2\n"
        "           _MinAltitude = -1000\n"
        "           _MaxAltitude = 20000\n"
        "           _RangePow = 4\n"
        "           LODs\n"
        "           {\n"
        "               LOD\n"
        "               {\n"
        "                   model = InfiniteDiscoveries/Visuals/Parallax/Models/Rocks/RockJagged/rock1\n"
        "                   _MainTex = parent\n"
        "                   range = 200\n"
        "                   billboard = False\n"
        "               }\n"
        "               LOD\n"
        "               {\n"
        "                   model = InfiniteDiscoveries/Visuals/Parallax/Models/Rocks/RockJagged/rock1\n"
        "                   _MainTex = parent\n"
        "                   range = 500\n"
        "                   billboard = False\n"
        "               }\n"
        "           }\n"
        "       }\n"
        "       Material\n"
        "       {\n"
        "           shader = Custom/ParallaxInstancedUV\n"
        "           _MainColor = 1,1,1,1\n"
        "           _SubColor = 1,1,1,1\n"
        "           _ColorNoiseStrength = 1\n"
        "           _MainTex = InfiniteDiscoveries/Visuals/Parallax/Models/Rocks/RockJagged/textureclr.dds\n"
        "           _EdgeBumpMap = InfiniteDiscoveries/Visuals/Parallax/Models/Rocks/RockJagged/texturenrm.dds\n"
        "           _Metallic = 0.25\n"
        "           _Gloss = 2\n"
        "           _NormalSpecularInfluence = 1\n"
        "           _Hapke = 1\n"
        "           _BumpScale = 1\n"
        "           _FresnelPower = 4\n"
        "           _MainTexScale = 1,1\n"
        "           _EdgeBumpMapScale = 1,1\n"
        "           _EmissionColor = 0,0,0,1\n"
        "           _MetallicTint = 0.5,0.5,0.5,1\n"
        "           _Color = 0.5,0.5,0.5,1\n"
        "           _FresnelColor = 0.2,0.2,0.2,1\n"
        "       }\n"
        "       SubObjects\n"
        "       {\n"
        "       }\n"
        "   }\n"
    )   
    if haslife == "organic":
        cfg.write(
            "   Scatter\n"
            "   {\n"
            "       name = Fern\n"
            "       model = InfiniteDiscoveries/Visuals/Parallax/Models/Foilage/Fern1/fern\n"
            "       updateFPS = 1\n"
            "       cullingRange = 20\n"
            "       cullingLimit = -30\n"
            "       alignToTerrainNormal = True\n"
            "       maxObjects = 20000\n"
            "       SubdivisionSettings\n"
            "       {\n"
            "           subdivisionLevel = 1\n"
            "           subdivisionRangeMode = FixedRange\n"
            "           subdivisionRange = 1400\n"
            "       }\n"
            "       DistributionNoise\n"
            "       {\n"
            "           mode = NonPersistent\n"
            "           _SizeNoiseScale = 4\n"
            "           _ColorNoiseScale = 32\n"
            "           _SizeNoiseOffset = 0\n"
            "       }\n"
            "       Distribution\n"
            "       {\n"
            "           _Seed = 0\n"
            "           _SpawnChance = 1\n"
            "           _Range = 1200\n"
            "           _PopulationMultiplier = "+ str((100/radiusDiv)/radiusDiv) + "\n"
            "           _SizeNoiseStrength = 2\n"
            "           _MinScale = 0.1,0.1,0.1\n"
            "           _MaxScale = 1,1,1\n"
            "           _CutoffScale = 0.75\n"
            "           _SteepPower = 8\n"
            "           _SteepContrast = 4.5\n"
            "           _SteepMidpoint = 0.731000006\n"
            "           _NormalDeviance = 0.2\n"
            "           _MinAltitude = 0\n"
            "           _MaxAltitude = 20000\n"
            "           _RangePow = 4\n"
            "           LODs\n"
            "           {\n"
            "               LOD\n"
            "               {\n"
            "                   model = InfiniteDiscoveries/Visuals/Parallax/Models/Foilage/Fern1/fern1\n"
            "                   _MainTex = parent\n"
            "                   range = 200\n"
            "                   billboard = False\n"
            "               }\n"
            "               LOD\n"
            "               {\n"
            "                   model = InfiniteDiscoveries/Visuals/Parallax/Models/Foilage/Fern1/fern1\n"
            "                   _MainTex = parent\n"
            "                   range = 500\n"
            "                   billboard = False\n"
            "               }\n"
            "           }\n"
            "           BiomeBlacklist\n"
            "           {\n"
            "               name = Icecaps\n"
            "           }\n"
            "       }\n"
            "       Material\n"
            "       {\n"
            "           shader = Custom/InstancedCutout\n"
            "           _MainColor = 1,1,1,1\n"
            "           _SubColor = 1,1,1,1\n"
            "           _ColorNoiseStrength = 1\n"
            "           _MainTex = InfiniteDiscoveries/Visuals/Parallax/Models/Foilage/Fern1/textureclr.dds\n"
            "           _BumpMap = InfiniteDiscoveries/Visuals/Parallax/Models/Foilage/Fern1/texturenrm.dds\n"
            "           _WindMap = Parallax_StockTextures/_Scatters/PluginData/grassuv2.dds\n"
            "           _WaveSpeed = 0\n"
            "           _WaveAmp = 0.0399999991\n"
            "           _HeightCutoff = -0.898999989\n"
            "           _HeightFactor = 2.25999999\n"
            "           _Metallic = 0.5\n"
            "           _Gloss = 5\n"
            "           _Hapke = 1\n"
            "           _Cutoff = 0.5\n"
            "           _WindSpeed = 50,50,50\n"
            "           _Color = " + str(lifeclr[0]) + "," + str(lifeclr[1]) + "," + str(lifeclr[2]) + "\n"
            "           _MetallicTint = 0.100000001,0.100000001,0.100000001,1\n"
            "           _FresnelPower = 3\n"
            "           _FresnelColor = 0.05,0.05,0.05\n"
            "           _Transmission = 1\n"
            "       }\n"
            "       SubObjects\n"
            "       {\n"
            "       }\n"
            "   }\n"
        )
        if pSctrRNG.randint(0,1) == 0:
            print("Has regular trees!")
            cfg.write(
                "   Scatter\n"
                "   {\n"
                "       name = tree1\n"
                "       model = InfiniteDiscoveries/Visuals/Parallax/Models/Trees/Oak1/trunk\n"
                "       updateFPS = 0.330000013\n"
                "       cullingRange = 200\n"
                "       cullingLimit = -400\n"
                "       alignToTerrainNormal = False\n"
                "       maxObjects = 40000\n"
                "       SubdivisionSettings\n"
                "       {\n"
                "           subdivisionLevel = 1\n"
                "           subdivisionRangeMode = FixedRange\n"
                "           subdivisionRange = 12500\n"
                "           minimumSubdivision = 8\n"
                "       }\n"
                "       DistributionNoise\n"
                "       {\n"
                "           mode = Persistent\n"
                "           _Frequency = 200\n"
                "           _Persistence = 0.300000012\n"
                "           _Lacunarity = 2\n"
                "           _Octaves = 6\n"
                "           _Seed = " + str(pSctrRNG.randint(0,10000)) + "\n"
                "           _NoiseType = 1\n"
                "           _NoiseQuality = Standard\n"
                "       }\n"
                "       Distribution\n"
                "       {\n"
                "           _Seed = 62.1199989\n"
                "           _SpawnChance = 0.699999988\n"
                "           _Range = 10500\n"
                "           _PopulationMultiplier = "+ str((5/radiusDiv)/radiusDiv) + "\n"
                "           _SizeNoiseStrength = 0.75\n"
                "           _MinScale = 1,1,1\n"
                "           _MaxScale = 3,3,3\n"
                "           _CutoffScale = 0.550000012\n"
                "           _SteepPower = 8\n"
                "           _SteepContrast = 4.5\n"
                "           _SteepMidpoint = 0.731000006\n"
                "           _NormalDeviance = 0.5\n"
                "           _MinAltitude = 0\n"
                "           _MaxAltitude = 20000\n"
                "           _RangePow = 250\n"
                "           LODs\n"
                "           {\n"
                "               LOD\n"
                "               {\n"
                "                   model = InfiniteDiscoveries/Visuals/Parallax/Models/Trees/Oak1/trunk1\n"
                "                   _MainTex = parent\n"
                "                   range = 250\n"
                "                   billboard = False\n"
                "               }\n"
                "               LOD\n"
                "               {\n"
                "                   model = InfiniteDiscoveries/Visuals/Parallax/Models/Trees/Oak1/farside\n"
                "                   _MainTex = InfiniteDiscoveries/Visuals/Parallax/Models/Trees/Oak1/treeside.dds\n"
                "                   _BumpMap = InfiniteDiscoveries/Visuals/Parallax/Models/Trees/Oak1/treeside_nrm.dds\n"
                "                   range = 2250\n"
                "                   billboard = True\n"
                "               }\n"
                "           }\n"
                "           BiomeBlacklist\n"
                "           {\n"
                "               name = Icecaps\n"
                "           }\n"
                "       }\n"
                "       Material\n"
                "       {\n"
                "           shader = Custom/InstancedCutout\n"
                "           _MainColor = 1,1,1,1\n"
                "           _SubColor = 1,1,1,1\n"
                "           _ColorNoiseStrength = 1\n"
                "           _MainTex = InfiniteDiscoveries/Visuals/Parallax/Models/Trees/Oak1/trunkclr.dds\n"
                "           _BumpMap = InfiniteDiscoveries/Visuals/Parallax/Models/Trees/Oak1/trunknrm.dds\n"
                "           _WindMap = Parallax_StockTextures/_Scatters/PluginData/grassuv2.dds\n"
                "           _WaveSpeed = 0\n"
                "           _WaveAmp = 0.0399999991\n"
                "           _HeightCutoff = -0.898999989\n"
                "           _HeightFactor = 2.25999999\n"
                "           _Metallic = 0.5\n"
                "           _Gloss = 5\n"
                "           _Hapke = 1\n"
                "           _Cutoff = 0.5\n"
                "           _WindSpeed = 50,50,50\n"
                "           _Color = " + str(lifeclr[0]) + "," + str(lifeclr[1]) + "," + str(lifeclr[2]) + "\n"
                "           _MetallicTint = 0.100000001,0.100000001,0.100000001,1\n"
                "           _FresnelPower = 3\n"
                "           _FresnelColor = 0.05,0.05,0.05\n"
                "           _Transmission = 1\n"
                "       }\n"
                "       SubObjects\n"
                "       {\n"
                "       }\n"
                "   }\n"
                "   SharedScatter	//Share the same distribution data as the tree1 scatter\n"
                "   {\n"
                "       parent = tree1\n"
                "       name = tree1top\n"
                "       model = InfiniteDiscoveries/Visuals/Parallax/Models/Trees/Oak1/leaves\n"
                "       Distribution\n"
                "       {\n"
                "           LODs\n"
                "           {\n"
                "               LOD\n"
                "               {\n"
                "                   model = InfiniteDiscoveries/Visuals/Parallax/Models/Trees/Oak1/leaves\n"
                "                   _MainTex = parent\n"
                "                   billboard = False\n"
                "               }\n"
                "               LOD\n"
                "               {\n"
                "                   model = InfiniteDiscoveries/Visuals/Parallax/Models/Trees/Oak1/fartop\n"
                "                   //_MainTex = InfiniteDiscoveries/Visuals/Parallax/Models/Trees/Oak1/leavesclr.dds\n"
                "                   billboard = False\n"
                "               }\n"
                "           }\n"
                "       }\n"
                "       Material\n"
                "       {\n"
                "           shader = Custom/InstancedCutout\n"
                "           _MainColor = 1,1,1,1\n"
                "           _SubColor = 1,1,1,1\n"
                "           _ColorNoiseStrength = 1\n"
                "           _MainTex = InfiniteDiscoveries/Visuals/Parallax/Models/Trees/Oak1/leavesclr.dds\n"
                "           _BumpMap = InfiniteDiscoveries/Visuals/Parallax/Models/Trees/Oak1/leavesnrm.dds\n"
                "           _WindMap = Parallax_StockTextures/_Scatters/PluginData/grassuv2.dds\n"
                "           _WaveSpeed = 0\n"
                "           _WaveAmp = 0.0399999991\n"
                "           _HeightCutoff = -0.898999989\n"
                "           _HeightFactor = 2.25999999\n"
                "           _Metallic = 0.5\n"
                "           _Gloss = 5\n"
                "           _Hapke = 1\n"
                "           _Cutoff = 0.5\n"
                "           _WindSpeed = 50,50,50\n"
                "           _Color = " + str(lifeclr[0]) + "," + str(lifeclr[1]) + "," + str(lifeclr[2]) + "\n"
                "           _MetallicTint = 0.100000001,0.100000001,0.100000001,1\n"
                "           _FresnelPower = 3\n"
                "           _FresnelColor = 0.05,0.05,0.05\n"
                "           _Transmission = 1\n"
                "       }\n"
                "   }\n"
            )
        if pSctrRNG.randint(0,1) == 0:
            cfg.write(
                "   Scatter\n"
                "   {\n"
                "       name = palm1\n"
                "       model = InfiniteDiscoveries/Visuals/Parallax/Models/Trees/Palm1/trunk\n"
                "       updateFPS = 0.330000013\n"
                "       cullingRange = 200\n"
                "       cullingLimit = -400\n"
                "       alignToTerrainNormal = False\n"
                "       maxObjects = 40000\n"
                "       SubdivisionSettings\n"
                "       {\n"
                "           subdivisionLevel = 1\n"
                "           subdivisionRangeMode = FixedRange\n"
                "           subdivisionRange = 12500\n"
                "           minimumSubdivision = 8\n"
                "       }\n"
                "       DistributionNoise\n"
                "       {\n"
                "           mode = Persistent\n"
                "           _Frequency = 200\n"
                "           _Persistence = 0.300000012\n"
                "           _Lacunarity = 2\n"
                "           _Octaves = 6\n"
                "           _Seed = " + str(pSctrRNG.randint(0,10000)) + "\n"
                "           _NoiseType = 1\n"
                "           _NoiseQuality = Standard\n"
                "       }\n"
                "       Distribution\n"
                "       {\n"
                "           _Seed = 62.1199989\n"
                "           _SpawnChance = 0.699999988\n"
                "           _Range = 10500\n"
                "           _PopulationMultiplier = "+ str((5/radiusDiv)/radiusDiv) + "\n"
                "           _SizeNoiseStrength = 0.75\n"
                "           _MinScale = 1,1,1\n"
                "           _MaxScale = 3,3,3\n"
                "           _CutoffScale = 0.550000012\n"
                "           _SteepPower = 8\n"
                "           _SteepContrast = 4.5\n"
                "           _SteepMidpoint = 0.731000006\n"
                "           _NormalDeviance = 0.5\n"
                "           _MinAltitude = 0\n"
                "           _MaxAltitude = 20000\n"
                "           _RangePow = 250\n"
                "           LODs\n"
                "           {\n"
                "               LOD\n"
                "               {\n"
                "                   model = InfiniteDiscoveries/Visuals/Parallax/Models/Trees/Palm1/trunk1\n"
                "                   _MainTex = parent\n"
                "                   range = 250\n"
                "                   billboard = False\n"
                "               }\n"
                "               LOD\n"
                "               {\n"
                "                   model = InfiniteDiscoveries/Visuals/Parallax/Models/Trees/Palm1/farside\n"
                "                   _MainTex = InfiniteDiscoveries/Visuals/Parallax/Models/Trees/Palm1/treeside.dds\n"
                "                   _BumpMap = InfiniteDiscoveries/Visuals/Parallax/Models/Trees/Palm1/treeside_nrm.dds\n"
                "                   range = 2250\n"
                "                   billboard = True\n"
                "               }\n"
                "           }\n"
                "           BiomeBlacklist\n"
                "           {\n"
                "               name = Icecaps\n"
                "           }\n"
                "       }\n"
                "       Material\n"
                "       {\n"
                "           shader = Custom/InstancedCutout\n"
                "           _MainColor = 1,1,1,1\n"
                "           _SubColor = 1,1,1,1\n"
                "           _ColorNoiseStrength = 1\n"
                "           _MainTex = InfiniteDiscoveries/Visuals/Parallax/Models/Trees/Palm1/trunkclr.dds\n"
                "           _BumpMap = InfiniteDiscoveries/Visuals/Parallax/Models/Trees/Palm1/trunknrm.dds\n"
                "           _WindMap = Parallax_StockTextures/_Scatters/PluginData/grassuv2.dds\n"
                "           _WaveSpeed = 0\n"
                "           _WaveAmp = 0.0399999991\n"
                "           _HeightCutoff = -0.898999989\n"
                "           _HeightFactor = 2.25999999\n"
                "           _Metallic = 0.5\n"
                "           _Gloss = 5\n"
                "           _Hapke = 1\n"
                "           _Cutoff = 0.5\n"
                "           _WindSpeed = 50,50,50\n"
                "           _Color = " + str(lifeclr[0]) + "," + str(lifeclr[1]) + "," + str(lifeclr[2]) + "\n"
                "           _MetallicTint = 0.100000001,0.100000001,0.100000001,1\n"
                "           _FresnelPower = 3\n"
                "           _FresnelColor = 0.05,0.05,0.05\n"
                "           _Transmission = 1\n"
                "       }\n"
                "       SubObjects\n"
                "       {\n"
                "       }\n"
                "   }\n"
                "   SharedScatter	//Share the same distribution data as the palm1 scatter\n"
                "   {\n"
                "       parent = palm1\n"
                "       name = palm1top\n"
                "       model = InfiniteDiscoveries/Visuals/Parallax/Models/Trees/Palm1/leaves\n"
                "       Distribution\n"
                "       {\n"
                "           LODs\n"
                "           {\n"
                "               LOD\n"
                "               {\n"
                "                   model = InfiniteDiscoveries/Visuals/Parallax/Models/Trees/Palm1/leaves\n"
                "                   _MainTex = parent\n"
                "                   billboard = False\n"
                "               }\n"
                "               LOD\n"
                "               {\n"
                "                   model = InfiniteDiscoveries/Visuals/Parallax/Models/Trees/Palm1/fartop\n"
                "                   _MainTex = InfiniteDiscoveries/Visuals/Parallax/Models/Trees/Palm1/treetop.dds\n"
                "                   _BumpMap = InfiniteDiscoveries/Visuals/Parallax/Models/Trees/Palm1/treetop_nrm.dds\n"
                "                   billboard = False\n"
                "               }\n"
                "           }\n"
                "       }\n"
                "       Material\n"
                "       {\n"
                "           shader = Custom/InstancedCutout\n"
                "           _MainColor = 1,1,1,1\n"
                "           _SubColor = 1,1,1,1\n"
                "           _ColorNoiseStrength = 1\n"
                "           _MainTex = InfiniteDiscoveries/Visuals/Parallax/Models/Trees/Palm1/leavesclr.dds\n"
                "           _BumpMap = InfiniteDiscoveries/Visuals/Parallax/Models/Trees/Palm1/leavesnrm.dds\n"
                "           _WindMap = Parallax_StockTextures/_Scatters/PluginData/grassuv2.dds\n"
                "           _WaveSpeed = 0\n"
                "           _WaveAmp = 0.0399999991\n"
                "           _HeightCutoff = -0.898999989\n"
                "           _HeightFactor = 2.25999999\n"
                "           _Metallic = 0.5\n"
                "           _Gloss = 5\n"
                "           _Hapke = 1\n"
                "           _Cutoff = 0.5\n"
                "           _WindSpeed = 50,50,50\n"
                "           _Color = " + str(lifeclr[0]) + "," + str(lifeclr[1]) + "," + str(lifeclr[2]) + "\n"
                "           _MetallicTint = 0.100000001,0.100000001,0.100000001,1\n"
                "           _FresnelPower = 3\n"
                "           _FresnelColor = 0.05,0.05,0.05\n"
                "           _Transmission = 1\n"
                "       }\n"
                "   }\n"
            )
        if pSctrRNG.randint(1,1) == 1:
            cfg.write(
                "   Scatter\n"
                "   {\n"
                "       name = BigTree\n"
                "       model = InfiniteDiscoveries/Visuals/Parallax/Models/Special/BigTree/trunk\n"
                "       updateFPS = 0.330000013\n"
                "       cullingRange = 200\n"
                "       cullingLimit = -400\n"
                "       alignToTerrainNormal = False\n"
                "       collideable = True\n"
                "       maxObjects = 40000\n"
                "       collisionMesh = InfiniteDiscoveries/Visuals/Parallax/Models/Special/BigTree/trunk\n"
                "       SubdivisionSettings\n"
                "       {\n"
                "           subdivisionLevel = 1\n"
                "           subdivisionRangeMode = FixedRange\n"
                "           subdivisionRange = 12500\n"
                "           minimumSubdivision = 8\n"
                "       }\n"
                "       DistributionNoise\n"
                "       {\n"
                "           mode = Persistent\n"
                "           _Frequency = 200\n"
                "           _Persistence = 0.300000012\n"
                "           _Lacunarity = 2\n"
                "           _Octaves = 6\n"
                "           _Seed = " + str(pSctrRNG.randint(0,10000)) + "\n"
                "           _NoiseType = 1\n"
                "           _NoiseQuality = Standard\n"
                "       }\n"
                "       Distribution\n"
                "       {\n"
                "           _Seed = 62.1199989\n"
                "           _SpawnChance = 0.01\n"
                "           _Range = 10500\n"
                "           _PopulationMultiplier = "+ str((1/radiusDiv)/radiusDiv) + "\n"
                "           _SizeNoiseStrength = 0.75\n"
                "           _MinScale = 1,1,1\n"
                "           _MaxScale = 200,200,200\n"
                "           _CutoffScale = 0.550000012\n"
                "           _SteepPower = 8\n"
                "           _SteepContrast = 4.5\n"
                "           _SteepMidpoint = 0.731000006\n"
                "           _NormalDeviance = 0.5\n"
                "           _MinAltitude = 0\n"
                "           _MaxAltitude = 20000\n"
                "           _RangePow = 250\n"
                "           LODs\n"
                "           {\n"
                "               LOD\n"
                "               {\n"
                "                   model = InfiniteDiscoveries/Visuals/Parallax/Models/Special/BigTree/trunk1\n"
                "                   _MainTex = parent\n"
                "                   range = 2500\n"
                "                   billboard = False\n"
                "               }\n"
                "               LOD\n"
                "               {\n"
                "                   model = InfiniteDiscoveries/Visuals/Parallax/Models/Special/BigTree/farside\n"
                "                   _MainTex = InfiniteDiscoveries/Visuals/Parallax/Models/Special/BigTree/treeside.dds\n"
                "                   _BumpMap = InfiniteDiscoveries/Visuals/Parallax/Models/Special/BigTree/treeside_nrm.dds\n"
                "                   range = 10000\n"
                "                   billboard = True\n"
                "               }\n"
                "           }\n"
                "       }\n"
                "       Material\n"
                "       {\n"
                "           shader = Custom/InstancedCutout\n"
                "           _MainColor = 1,1,1,1\n"
                "           _SubColor = 1,1,1,1\n"
                "           _ColorNoiseStrength = 1\n"
                "           _MainTex = InfiniteDiscoveries/Visuals/Parallax/Models/Special/BigTree/trunkclr.dds\n"
                "           _BumpMap = InfiniteDiscoveries/Visuals/Parallax/Models/Special/BigTree/trunknrm.dds\n"
                "           _WindMap = Parallax_StockTextures/_Scatters/PluginData/grassuv2.dds\n"
                "           _WaveSpeed = 0\n"
                "           _WaveAmp = 0.0399999991\n"
                "           _HeightCutoff = -0.898999989\n"
                "           _HeightFactor = 2.25999999\n"
                "           _Metallic = 0.5\n"
                "           _Gloss = 5\n"
                "           _Hapke = 1\n"
                "           _Cutoff = 0.5\n"
                "           _WindSpeed = 50,50,50\n"
                "           _Color = " + str(lifeclr[0]) + "," + str(lifeclr[1]) + "," + str(lifeclr[2]) + "\n"
                "           _MetallicTint = 0.100000001,0.100000001,0.100000001,1\n"
                "           _FresnelPower = 3\n"
                "           _FresnelColor = 0.05,0.05,0.05\n"
                "           _Transmission = 1\n"
                "       }\n"
                "       SubObjects\n"
                "       {\n"
                "       }\n"
                "   }\n"
                "   SharedScatter	//Share the same distribution data as the stupid big ass tree scatter\n"
                "   {\n"
                "       parent = BigTree\n"
                "       name = BigTreeTop\n"
                "       model = InfiniteDiscoveries/Visuals/Parallax/Models/Special/BigTree/leaves\n"
                "       Distribution\n"
                "       {\n"
                "           LODs\n"
                "           {\n"
                "               LOD\n"
                "               {\n"
                "                   model = InfiniteDiscoveries/Visuals/Parallax/Models/Special/BigTree/leaves\n"
                "                   _MainTex = parent\n"
                "                   billboard = False\n"
                "               }\n"
                "               LOD\n"
                "               {\n"
                "                   model = InfiniteDiscoveries/Visuals/Parallax/Models/Special/BigTree/fartop\n"
                "                   _MainTex = InfiniteDiscoveries/Visuals/Parallax/Models/Special/BigTree/treetop.dds\n"
                "                   _BumpMap = InfiniteDiscoveries/Visuals/Parallax/Models/Special/BigTree/treetop_nrm.dds\n"
                "                   billboard = False\n"
                "               }\n"
                "           }\n"
                "       }\n"
                "       Material\n"
                "       {\n"
                "           shader = Custom/InstancedCutout\n"
                "           _MainColor = 1,1,1,1\n"
                "           _SubColor = 1,1,1,1\n"
                "           _ColorNoiseStrength = 1\n"
                "           _MainTex = InfiniteDiscoveries/Visuals/Parallax/Models/Special/BigTree/leavesclr.dds\n"
                "           _BumpMap = InfiniteDiscoveries/Visuals/Parallax/Models/Special/BigTree/leavesnrm.dds\n"
                "           _WindMap = Parallax_StockTextures/_Scatters/PluginData/grassuv2.dds\n"
                "           _WaveSpeed = 0\n"
                "           _WaveAmp = 0.0399999991\n"
                "           _HeightCutoff = -0.898999989\n"
                "           _HeightFactor = 2.25999999\n"
                "           _Metallic = 0.5\n"
                "           _Gloss = 5\n"
                "           _Hapke = 1\n"
                "           _Cutoff = 0.5\n"
                "           _WindSpeed = 50,50,50\n"
                "           _Color = " + str(lifeclr[0]) + "," + str(lifeclr[1]) + "," + str(lifeclr[2]) + "\n"
                "           _MetallicTint = 0.100000001,0.100000001,0.100000001,1\n"
                "           _FresnelPower = 3\n"
                "           _FresnelColor = 0.05,0.05,0.05\n"
                "           _Transmission = 1\n"
                "       }\n"
                "   }\n"
            )
    cfg.write(
        "}\n"
    )
# This is required to make parallax scatters work lmfao
def addToParallaxScatterFixCfg(cfg, planetName):
    cfg.write(
        "   @Body[" + planetName + "]\n"
        "   {\n"
        "       %PQS\n"
        "       {\n"
        "           %Mods\n"
        "           {\n"
        "               ParallaxScatter\n"
        "               {\n"
        "                   order = 999999\n"
        "               }\n"
        "               ScatterDistribute\n"
        "               {\n"
        "                   order = 999998\n"
        "               }\n"
        "           }\n"
        "       }\n"
        "   }\n"
    )

# Adds a subdivision fix for Parallax support.
def addSubdividerFix(subdFixCfg, planetName):
    subdFixCfg.write(
        "   @Body[" + planetName + "]\n"
        "   {\n"
        "       %PQS\n"
        "       {\n"
        "           %Mods\n"
        "           {\n"
        "               Subdivide\n"
        "               {\n"
        "                   subdivisionLevel = 36\n"
        "                   subdivisionRadius = 150\n"
        "                   //advancedSubdivisionLevel = 64\n"
        "                   order = 999999\n"
        "               }\n"
        "           }\n"
        "       }\n"
        "   }\n"
    )

import time, state

# Writes the actual Parallax config.
def addToParallaxCfg(seed, parallaxCfg, planetName, lava, lavaClr, groundType, icy, allActions):
    ParallaxRNG = random.Random()
    ParallaxRNG.seed(seed)

    #                [Name, [Variant, Scale, Displacement].
    allGroundTypes = [["Gravel",[[1,1,0.075]]],
                        ["Sand",[[1,1,0.075]]],
                        ["Rock",[[1,1.25,0.05]]],
                        ["Ice",[[1,1,0.05]]]]
    groundChoice = allGroundTypes[groundType][0]
    variantList = allGroundTypes[groundType][1]
    possibleValues = len(variantList)
    randomVar = ParallaxRNG.randint(0,possibleValues-1)

    allActions.append([time.localtime(),"Writing parallax config for : " + planetName])

    state.allActionArrayUpdated = True
    if lava == False:
        parallaxCfg.write(
            "    Body\n"
            "    {\n"
            "        name = " + planetName + "\n"
            "        emissive = false\n"
            "        Textures\n"
            "        {\n"
            "            _SurfaceTextureScale = " + str(allGroundTypes[groundType][1][randomVar][1]) + "\n"
            "    \n"
            "            _SurfaceTexture = InfiniteDiscoveries/Visuals/Parallax/Textures/" + groundChoice + "/Var" + str(randomVar+1) + "/CLR.dds\n"
            "            _SurfaceTextureMid = InfiniteDiscoveries/Visuals/Parallax/Textures/" + groundChoice + "/Var" + str(randomVar+1) + "/CLR.dds\n"
            "            _SurfaceTextureHigh = InfiniteDiscoveries/Visuals/Parallax/Textures/" + groundChoice + "/Var" + str(randomVar+1) + "/CLR.dds\n"
            "            _SteepTex = InfiniteDiscoveries/Visuals/Parallax/Textures/" + groundChoice + "/Var" + str(randomVar+1) + "/CLR.dds\n"
            "    \n"
            "            _BumpMap = InfiniteDiscoveries/Visuals/Parallax/Textures/" + groundChoice + "/Var" + str(randomVar+1) + "/NRM.dds\n"
            "            _BumpMapMid = InfiniteDiscoveries/Visuals/Parallax/Textures/" + groundChoice + "/Var" + str(randomVar+1) + "/NRM.dds\n"
            "            _BumpMapHigh = InfiniteDiscoveries/Visuals/Parallax/Textures/" + groundChoice + "/Var" + str(randomVar+1) + "/NRM.dds\n"
            "            _BumpMapSteep = InfiniteDiscoveries/Visuals/Parallax/Textures/" + groundChoice + "/Var" + str(randomVar+1) + "/NRM.dds\n"
            "    \n"
            "            _DispTex = InfiniteDiscoveries/Visuals/Parallax/Textures/" + groundChoice + "/Var" + str(randomVar+1) + "/DSP.dds\n"
            "            _InfluenceMap = InfiniteDiscoveries/Visuals/Parallax/Textures/" + groundChoice + "/Var" + str(randomVar+1) + "/INF.dds\n"
            "    \n"
            "            _displacement_scale = " + str(allGroundTypes[groundType][1][randomVar][2]) + "\n"
            "            _displacement_offset = 0\n"
            "    \n"
            "            _SteepPower = 4\n"
            "            _SteepContrast = 4\n"
            "            _SteepMidpoint = 0.6\n"
            "    \n"
        )
        if icy == True:
            parallaxCfg.write(
                "            _Metallic = 1\n"
                "            _MetallicTint = 0.6,0.6,0.6\n"
                "            _Gloss = 60\n"
                "            _NormalSpecularInfluence = 0.75\n"
            )
        else:
            parallaxCfg.write(
                "            _Metallic = 0.08\n"
                "            _MetallicTint = 0.6,0.6,0.6\n"
                "            _Gloss = 22\n"
                "            _NormalSpecularInfluence = 1\n"
            )
        parallaxCfg.write(
            "            _Hapke = 1\n"
            "            _EmissionColor = 0, 0, 0\n"
            "    \n"
            "            _FresnelColor = 0.1,0.1,0.1\n"
            "            _FresnelPower = 3\n"
            "    \n"
            "            _LowStart = 0\n"
            "            _LowEnd = 1\n"
            "            _HighStart = 3000\n"
            "            _HighEnd = 3350\n"
            "        }\n"
            "    }\n"
        )
    elif lava == True:
        parallaxCfg.write(
            "   Body\n"
            "   {\n"
            "       name = " + planetName + "\n"
            "       emissive = true\n"
            "       Textures\n"
            "       {\n"
            "           _SurfaceTextureScale = 0.5\n"
            "   \n"
            "           _SurfaceTexture = InfiniteDiscoveries/Visuals/Parallax/Textures/Lava/Var1/CLR.dds\n"
            "           _SurfaceTextureMid = InfiniteDiscoveries/Visuals/Parallax/Textures/Lava/Var1/CLR.dds\n"
            "           _SurfaceTextureHigh = InfiniteDiscoveries/Visuals/Parallax/Textures/Lava/Var1/CLR.dds\n"
            "           _SteepTex = InfiniteDiscoveries/Visuals/Parallax/Textures/Lava/Var1/CLR.dds\n"
            "   \n"
            "           _BumpMap = InfiniteDiscoveries/Visuals/Parallax/Textures/Lava/Var1/NRM_E.dds\n"
            "           _BumpMapMid = InfiniteDiscoveries/Visuals/Parallax/Textures/Lava/Var1/NRM.dds\n"
            "           _BumpMapHigh = InfiniteDiscoveries/Visuals/Parallax/Textures/Lava/Var1/NRM.dds\n"
            "           _BumpMapSteep = InfiniteDiscoveries/Visuals/Parallax/Textures/Lava/Var1/NRM.dds\n"
            "   \n"
            "           _DispTex = InfiniteDiscoveries/Visuals/Parallax/Textures/Lava/Var1/DSP.dds\n"
            "           _InfluenceMap = InfiniteDiscoveries/Visuals/Parallax/Textures/Lava/Var1/INF.dds\n"
            "   \n"
            "           _displacement_scale = 0.05\n"
            "           _displacement_offset = 0\n"
            "   \n"
            "           _SteepPower = 14\n"
            "           _SteepContrast = 4\n"
            "           _SteepMidpoint = 0.6\n"
            "   \n"
            "           _Metallic = 0.08\n"
            "           _MetallicTint = 0.6,0.6,0.6\n"
            "           _Gloss = 22\n"
            "           _NormalSpecularInfluence = 1\n"
            "           _Hapke = 1\n"
            "           _EmissionColor = " +  str(lavaClr[0]) + ", " + str(lavaClr[1]) + ", " + str(lavaClr[2]) + "\n"
            "   \n"
            "           _FresnelColor = 0.1,0.1,0.1\n"
            "           _FresnelPower = 3\n"
            "   \n"
            "           _LowStart = 0\n"
            "           _LowEnd = 1200\n"
            "           _HighStart = 3000\n"
            "           _HighEnd = 3350\n"
            "       }\n"
            "   }\n"
        )